using System.Collections.Generic;
using System.Text;

namespace Code.EcsStateMachine.Editor.CodeGeneration.Generation.Factories
{
    /// <summary>
    /// Generates factory code for creating ECS state change systems.
    /// </summary>
    public static class EcsStateChangeSystemsFactoryGenerator
    {
        /// <summary>
        /// Generates source code for EcsStateChangeSystemsFactory.
        /// </summary>
        public static string GenerateFactory(IReadOnlyDictionary<string, string> systems)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// This file was generated automatically. Changes to this file will be overwritten the next time code is generated.");
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();

            builder.AppendLine("using System;");
            builder.AppendLine("using Code.EcsStateMachine.Runtime.Logic.Abstractions;");
            builder.AppendLine();

            builder.AppendLine("namespace Code.EcsStateMachine.Runtime.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class EcsStateChangeSystemsFactory");
            builder.AppendLine("    {");

            builder.AppendLine("        public static IEcsStateChangeSystem Create(EcsStateChangeSystemsIds id)");
            builder.AppendLine("        {");
            builder.AppendLine("            return id switch");
            builder.AppendLine("            {");

            builder.AppendLine("                EcsStateChangeSystemsIds.None => null,");

            foreach (var system in systems)
            {
                builder.Append("                EcsStateChangeSystemsIds.");
                builder.Append(system.Key);
                builder.Append(" => Create(\"");
                builder.Append(system.Value);
                builder.AppendLine("\"),");
            }

            builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine();

            builder.AppendLine("        private static IEcsStateChangeSystem Create(string typeName)");
            builder.AppendLine("        {");
            builder.AppendLine("            Type type = null;");
            builder.AppendLine();

            builder.AppendLine("            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())");
            builder.AppendLine("            {");
            builder.AppendLine("                type = assembly.GetType(typeName);");
            builder.AppendLine();

            builder.AppendLine("                if (type != null)");
            builder.AppendLine("                {");
            builder.AppendLine("                    break;");
            builder.AppendLine("                }");
            builder.AppendLine("            }");

            builder.AppendLine();

            builder.AppendLine("            if (type == null)");
            builder.AppendLine("            {");
            builder.AppendLine(
                "                throw new InvalidOperationException($\"System type not found: {typeName}\");");
            builder.AppendLine("            }");

            builder.AppendLine();

            builder.AppendLine("            return (IEcsStateChangeSystem)Activator.CreateInstance(type);");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}