using System.Collections.Generic;
using System.Text;

namespace Code.Logic.CodeGeneration.Editor.Generation.Factories
{
    public sealed class EcsRunSystemFactoryGenerator
    {
        public static string GenerateFactory(IReadOnlyDictionary<string, string> systems)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();

            builder.AppendLine("using System;");
            builder.AppendLine("using Leopotam.EcsLite;");
            builder.AppendLine();

            builder.AppendLine("namespace Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class EcsRunSystemsFactory");
            builder.AppendLine("    {");
            builder.AppendLine("        public static IEcsRunSystem Create(EcsRunSystemsIds id)");
            builder.AppendLine("        {");
            builder.AppendLine("            return id switch");
            builder.AppendLine("            {");

            foreach (KeyValuePair<string, string> system in systems)
            {
                builder.Append("                EcsRunSystemsIds.");
                builder.Append(system.Key);
                builder.Append(" => new ");
                builder.Append(system.Value);
                builder.AppendLine("(),");
            }

            builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}