using System.Collections.Generic;
using System.Text;

namespace Code.Logic.CodeGeneration.Editor.Generation.Factories
{
    public sealed class EcsStateChangeSystemsFactoryGenerator
    {
        public static string GenerateFactory(IReadOnlyDictionary<string, string> systems)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();

            builder.AppendLine("using System;");
            builder.AppendLine("using Leopotam.EcsLite;");
            builder.AppendLine("using Code.Logic.Ecs.Interfaces;");
            builder.AppendLine();

            builder.AppendLine("namespace Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class EcsStateChangeSystemsFactory");
            builder.AppendLine("    {");

            builder.AppendLine("        public static IEcsStateChangeSystem Create(EcsStateChangeSystemsIds id)");
            builder.AppendLine("        {");

            builder.AppendLine("            return id switch");
            builder.AppendLine("            {");

            foreach (KeyValuePair<string, string> system in systems)
            {
                builder.Append("                EcsStateChangeSystemsIds.");
                builder.Append(system.Key);
                builder.Append(" => Create(\"");
                builder.Append(system.Value);
                builder.AppendLine("\"),");
            }

            builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");
            builder.AppendLine("            };");
            builder.AppendLine("        }");


            builder.AppendLine();
            builder.AppendLine("        private static IEcsStateChangeSystem Create(string typeName)");
            builder.AppendLine("        {");
            builder.AppendLine("            var type = Type.GetType(typeName);");
            builder.AppendLine();
            builder.AppendLine("            if (type == null)");
            builder.AppendLine("                return null;");
            builder.AppendLine();
            builder.AppendLine("            return Activator.CreateInstance(type) as IEcsStateChangeSystem;");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
        
        // public static string GenerateFactory(IReadOnlyDictionary<string, string> systems)
        // {
        //     var builder = new StringBuilder();
        //
        //     builder.AppendLine("// <auto-generated/>");
        //     builder.AppendLine();
        //
        //     builder.AppendLine("using System;");
        //     builder.AppendLine("using Leopotam.EcsLite;");
        //     builder.AppendLine("using Code.Logic.Ecs.Interfaces;");
        //     builder.AppendLine();
        //
        //     builder.AppendLine("namespace Generated");
        //     builder.AppendLine("{");
        //     builder.AppendLine("    public static class EcsStateChangeSystemsFactory");
        //     builder.AppendLine("    {");
        //     builder.AppendLine("        public static IEcsStateChangeSystem Create(EcsStateChangeSystemsIds id)");
        //     builder.AppendLine("        {");
        //     builder.AppendLine("            return id switch");
        //     builder.AppendLine("            {");
        //
        //     foreach (KeyValuePair<string, string> system in systems)
        //     {
        //         builder.Append("                EcsStateChangeSystemsIds.");
        //         builder.Append(system.Key);
        //         builder.Append(" => new ");
        //         builder.Append(system.Value);
        //         builder.AppendLine("(),");
        //     }
        //
        //     builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");
        //     builder.AppendLine("            };");
        //     builder.AppendLine("        }");
        //     builder.AppendLine("    }");
        //     builder.AppendLine("}");
        //
        //     return builder.ToString();
        // }
    }
}