using System.Collections.Generic;
using System.Text;

namespace Code.EcsStateMachine.CodeGeneration.Editor.Generation.Factories
{
    public sealed class EcsFeatureFactoryGenerator
    {
        public static string GenerateFactory(IReadOnlyDictionary<string, string> features)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();

            builder.AppendLine("using System;");
            builder.AppendLine("using Code.EcsStateMachine.Logic.Abstractions;");
            builder.AppendLine();

            builder.AppendLine("namespace Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class EcsFeatureFactory");
            builder.AppendLine("    {");

            builder.AppendLine("        public static EcsFeature Create(EcsFeatureIds id)");
            builder.AppendLine("        {");
            builder.AppendLine("            return id switch");
            builder.AppendLine("            {");

            builder.AppendLine("                EcsFeatureIds.None => null,");

            foreach (KeyValuePair<string, string> feature in features)
            {
                builder.Append("                EcsFeatureIds.");
                builder.Append(feature.Key);
                builder.Append(" => Create(\"");
                builder.Append(feature.Value);
                builder.AppendLine("\"),");
            }

            builder.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine();

            builder.AppendLine("        private static EcsFeature Create(string typeName)");
            builder.AppendLine("        {");
            builder.AppendLine("            var type = Type.GetType(typeName);");
            builder.AppendLine();

            builder.AppendLine("            if (type == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                throw new InvalidOperationException($\"Feature type not found: {typeName}\");");
            builder.AppendLine("            }");
            builder.AppendLine();

            builder.AppendLine("            return (EcsFeature)Activator.CreateInstance(type);");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}

