using System;
using System.Collections.Generic;
using System.Text;
using Code.EcsStateMachine.Editor.CodeGeneration.SourceGenerationData.Enums;
using Code.EcsStateMachine.Editor.CodeGeneration.SourceGenerationData.Utils;
using Code.EcsStateMachine.Editor.CodeGeneration.Utils;

namespace Code.EcsStateMachine.Editor.CodeGeneration.Generation
{
    /// <summary>
    /// Generates C# enum source code.
    /// </summary>
    internal static class EnumSourceGenerator
    {
        /// <summary>
        /// Creates enum definition from provided types.
        /// </summary>
        public static EnumDefinition CreateDefinition(List<Type> types, string enumName, string enumNamespace)
        {
            var values = new List<EnumValue>();
            var generatedIds = new Dictionary<int, string>();
            var nameCounts = TypeNameResolver.GetTypeNameOccurrences(types);

            foreach (var type in types)
            {
                var fullName = type.FullName ?? type.Name;
                var id = StableId.Get(fullName);

                if (generatedIds.TryGetValue(id, out var existingType))
                {
                    throw new Exception($"ID collision between {existingType} and {fullName}");
                }

                generatedIds.Add(id, fullName);

                values.Add(new EnumValue
                {
                    Name = TypeNameResolver.Resolve(type, nameCounts),
                    Value = id
                });
            }

            return new EnumDefinition
            {
                Namespace = enumNamespace,
                Name = enumName,
                Values = values
            };
        }

        /// <summary>
        /// Generates enum code from definition data.
        /// </summary>
        public static string Generate(EnumDefinition definition)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// This file was generated automatically. Changes to this file will be overwritten the next time code is generated.");
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine();

            builder.AppendLine($"namespace {definition.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public enum {definition.Name}");
            builder.AppendLine("    {");
            builder.AppendLine("        None,");

            foreach (var value in definition.Values)
            {
                builder.AppendLine($"        {value.Name} = {value.Value},");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}

