using System;
using System.Collections.Generic;
using System.Text;
using Code.EcsStateMachine.Editor.CodeGeneration.SourceGenerationData.Factories;
using Code.EcsStateMachine.Editor.CodeGeneration.SourceGenerationData.Utils;

namespace Code.EcsStateMachine.Editor.CodeGeneration.Generation
{
    /// <summary>
    /// Generates factory code for creating ECS objects from generated identifiers.
    /// </summary>
    internal static class FactorySourceGenerator
    {
        /// <summary>
        /// Generates factory source code from factory definition.
        /// </summary>
        public static string Generate(FactoryDefinition definition)
        {
            var typeMap = CreateTypeMap(definition.Types);

            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine(
                "// This file was generated automatically. Changes to this file will be overwritten the next time code is generated.");
            builder.AppendLine();

            builder.AppendLine("using System;");
            builder.AppendLine($"using {definition.ReturnType.Namespace};");
            builder.AppendLine();

            builder.AppendLine($"namespace {definition.Namespace}");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {definition.FactoryName}");
            builder.AppendLine("    {");

            builder.AppendLine($"        public static {definition.ReturnType.Name} Create({definition.EnumName} id)");

            builder.AppendLine("        {");
            builder.AppendLine("            return id switch");
            builder.AppendLine("            {");

            builder.AppendLine($"                {definition.EnumName}.None => null,");

            foreach (var type in typeMap)
            {
                builder.Append($"                {definition.EnumName}.{type.Key} => Create(\"");

                builder.Append(type.Value);

                builder.AppendLine("\"),");
            }

            builder.AppendLine(
                "                _ => throw new ArgumentOutOfRangeException(nameof(id), id, null)");

            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine();

            builder.AppendLine($"        private static {definition.ReturnType.Name} Create(string typeName)");

            builder.AppendLine("        {");
            builder.AppendLine("            Type type = null;");
            builder.AppendLine();

            builder.AppendLine("            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())");

            builder.AppendLine("            {");

            builder.AppendLine("                type = assembly.GetType(typeName);");

            builder.AppendLine();

            builder.AppendLine("                if (type != null)");
            builder.AppendLine("                {");
            builder.AppendLine("                    break;");
            builder.AppendLine("                }");

            builder.AppendLine("            }");

            builder.AppendLine();

            builder.AppendLine("            if (type == null)");
            builder.AppendLine("            {");

            builder.AppendLine("                throw new InvalidOperationException($\"Type not found: {typeName}\");");

            builder.AppendLine("            }");

            builder.AppendLine();

            builder.AppendLine($"            return ({definition.ReturnType.Name})Activator.CreateInstance(type);");

            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static Dictionary<string, string> CreateTypeMap(IReadOnlyList<Type> types)
        {
            var result = new Dictionary<string, string>();
            var nameOccurrences = TypeNameResolver.GetTypeNameOccurrences(types);

            foreach (var type in types)
            {
                var name = TypeNameResolver.Resolve(type, nameOccurrences);
                var fullName = type.FullName ?? type.Name;

                result.Add(name, fullName);
            }

            return result;
        }
    }
}